// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sawtooth_sdk/protobuf/client_transaction_pb2/client_transaction.proto

package client_transaction_pb2

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import client_list_control_pb2 "github.com/daludaluking/sawtooth_sdk/protobuf/client_list_control_pb2"
import transaction_pb2 "github.com/daludaluking/sawtooth_sdk/protobuf/transaction_pb2"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ClientTransactionListResponse_Status int32

const (
	ClientTransactionListResponse_STATUS_UNSET   ClientTransactionListResponse_Status = 0
	ClientTransactionListResponse_OK             ClientTransactionListResponse_Status = 1
	ClientTransactionListResponse_INTERNAL_ERROR ClientTransactionListResponse_Status = 2
	ClientTransactionListResponse_NOT_READY      ClientTransactionListResponse_Status = 3
	ClientTransactionListResponse_NO_ROOT        ClientTransactionListResponse_Status = 4
	ClientTransactionListResponse_NO_RESOURCE    ClientTransactionListResponse_Status = 5
	ClientTransactionListResponse_INVALID_PAGING ClientTransactionListResponse_Status = 6
	ClientTransactionListResponse_INVALID_SORT   ClientTransactionListResponse_Status = 7
	ClientTransactionListResponse_INVALID_ID     ClientTransactionListResponse_Status = 8
)

var ClientTransactionListResponse_Status_name = map[int32]string{
	0: "STATUS_UNSET",
	1: "OK",
	2: "INTERNAL_ERROR",
	3: "NOT_READY",
	4: "NO_ROOT",
	5: "NO_RESOURCE",
	6: "INVALID_PAGING",
	7: "INVALID_SORT",
	8: "INVALID_ID",
}
var ClientTransactionListResponse_Status_value = map[string]int32{
	"STATUS_UNSET":   0,
	"OK":             1,
	"INTERNAL_ERROR": 2,
	"NOT_READY":      3,
	"NO_ROOT":        4,
	"NO_RESOURCE":    5,
	"INVALID_PAGING": 6,
	"INVALID_SORT":   7,
	"INVALID_ID":     8,
}

func (x ClientTransactionListResponse_Status) String() string {
	return proto.EnumName(ClientTransactionListResponse_Status_name, int32(x))
}
func (ClientTransactionListResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_client_transaction_754fcaed5986d902, []int{1, 0}
}

type ClientTransactionGetResponse_Status int32

const (
	ClientTransactionGetResponse_STATUS_UNSET   ClientTransactionGetResponse_Status = 0
	ClientTransactionGetResponse_OK             ClientTransactionGetResponse_Status = 1
	ClientTransactionGetResponse_INTERNAL_ERROR ClientTransactionGetResponse_Status = 2
	ClientTransactionGetResponse_NO_RESOURCE    ClientTransactionGetResponse_Status = 5
	ClientTransactionGetResponse_INVALID_ID     ClientTransactionGetResponse_Status = 8
)

var ClientTransactionGetResponse_Status_name = map[int32]string{
	0: "STATUS_UNSET",
	1: "OK",
	2: "INTERNAL_ERROR",
	5: "NO_RESOURCE",
	8: "INVALID_ID",
}
var ClientTransactionGetResponse_Status_value = map[string]int32{
	"STATUS_UNSET":   0,
	"OK":             1,
	"INTERNAL_ERROR": 2,
	"NO_RESOURCE":    5,
	"INVALID_ID":     8,
}

func (x ClientTransactionGetResponse_Status) String() string {
	return proto.EnumName(ClientTransactionGetResponse_Status_name, int32(x))
}
func (ClientTransactionGetResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_client_transaction_754fcaed5986d902, []int{3, 0}
}

// A request to return a list of txns from the validator. May include the id
// of a particular block to be the `head` of the chain being requested. In that
// case the list will include the txns from that block, and all txns
// previous to that block on the chain. Filter with specific `transaction_ids`.
type ClientTransactionListRequest struct {
	HeadId               string                                        `protobuf:"bytes,1,opt,name=head_id,json=headId" json:"head_id,omitempty"`
	TransactionIds       []string                                      `protobuf:"bytes,2,rep,name=transaction_ids,json=transactionIds" json:"transaction_ids,omitempty"`
	Paging               *client_list_control_pb2.ClientPagingControls `protobuf:"bytes,3,opt,name=paging" json:"paging,omitempty"`
	Sorting              []*client_list_control_pb2.ClientSortControls `protobuf:"bytes,4,rep,name=sorting" json:"sorting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                      `json:"-"`
	XXX_unrecognized     []byte                                        `json:"-"`
	XXX_sizecache        int32                                         `json:"-"`
}

func (m *ClientTransactionListRequest) Reset()         { *m = ClientTransactionListRequest{} }
func (m *ClientTransactionListRequest) String() string { return proto.CompactTextString(m) }
func (*ClientTransactionListRequest) ProtoMessage()    {}
func (*ClientTransactionListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_client_transaction_754fcaed5986d902, []int{0}
}
func (m *ClientTransactionListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientTransactionListRequest.Unmarshal(m, b)
}
func (m *ClientTransactionListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientTransactionListRequest.Marshal(b, m, deterministic)
}
func (dst *ClientTransactionListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientTransactionListRequest.Merge(dst, src)
}
func (m *ClientTransactionListRequest) XXX_Size() int {
	return xxx_messageInfo_ClientTransactionListRequest.Size(m)
}
func (m *ClientTransactionListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientTransactionListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClientTransactionListRequest proto.InternalMessageInfo

func (m *ClientTransactionListRequest) GetHeadId() string {
	if m != nil {
		return m.HeadId
	}
	return ""
}

func (m *ClientTransactionListRequest) GetTransactionIds() []string {
	if m != nil {
		return m.TransactionIds
	}
	return nil
}

func (m *ClientTransactionListRequest) GetPaging() *client_list_control_pb2.ClientPagingControls {
	if m != nil {
		return m.Paging
	}
	return nil
}

func (m *ClientTransactionListRequest) GetSorting() []*client_list_control_pb2.ClientSortControls {
	if m != nil {
		return m.Sorting
	}
	return nil
}

// A response that lists transactions from newest to oldest.
//
// Statuses:
//   * OK - everything worked as expected
//   * INTERNAL_ERROR - general error, such as protobuf failing to deserialize
//   * NOT_READY - the validator does not yet have a genesis block
//   * NO_ROOT - the head block specified was not found
//   * NO_RESOURCE - no txns were found with the parameters specified
//   * INVALID_PAGING - the paging controls were malformed or out of range
//   * INVALID_SORT - the sorting controls were malformed or invalid
type ClientTransactionListResponse struct {
	Status               ClientTransactionListResponse_Status          `protobuf:"varint,1,opt,name=status,enum=ClientTransactionListResponse_Status" json:"status,omitempty"`
	Transactions         []*transaction_pb2.Transaction                `protobuf:"bytes,2,rep,name=transactions" json:"transactions,omitempty"`
	HeadId               string                                        `protobuf:"bytes,3,opt,name=head_id,json=headId" json:"head_id,omitempty"`
	Paging               *client_list_control_pb2.ClientPagingResponse `protobuf:"bytes,4,opt,name=paging" json:"paging,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                      `json:"-"`
	XXX_unrecognized     []byte                                        `json:"-"`
	XXX_sizecache        int32                                         `json:"-"`
}

func (m *ClientTransactionListResponse) Reset()         { *m = ClientTransactionListResponse{} }
func (m *ClientTransactionListResponse) String() string { return proto.CompactTextString(m) }
func (*ClientTransactionListResponse) ProtoMessage()    {}
func (*ClientTransactionListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_client_transaction_754fcaed5986d902, []int{1}
}
func (m *ClientTransactionListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientTransactionListResponse.Unmarshal(m, b)
}
func (m *ClientTransactionListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientTransactionListResponse.Marshal(b, m, deterministic)
}
func (dst *ClientTransactionListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientTransactionListResponse.Merge(dst, src)
}
func (m *ClientTransactionListResponse) XXX_Size() int {
	return xxx_messageInfo_ClientTransactionListResponse.Size(m)
}
func (m *ClientTransactionListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientTransactionListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClientTransactionListResponse proto.InternalMessageInfo

func (m *ClientTransactionListResponse) GetStatus() ClientTransactionListResponse_Status {
	if m != nil {
		return m.Status
	}
	return ClientTransactionListResponse_STATUS_UNSET
}

func (m *ClientTransactionListResponse) GetTransactions() []*transaction_pb2.Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *ClientTransactionListResponse) GetHeadId() string {
	if m != nil {
		return m.HeadId
	}
	return ""
}

func (m *ClientTransactionListResponse) GetPaging() *client_list_control_pb2.ClientPagingResponse {
	if m != nil {
		return m.Paging
	}
	return nil
}

// Fetches a specific txn by its id (header_signature) from the blockchain.
type ClientTransactionGetRequest struct {
	TransactionId        string   `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId" json:"transaction_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientTransactionGetRequest) Reset()         { *m = ClientTransactionGetRequest{} }
func (m *ClientTransactionGetRequest) String() string { return proto.CompactTextString(m) }
func (*ClientTransactionGetRequest) ProtoMessage()    {}
func (*ClientTransactionGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_client_transaction_754fcaed5986d902, []int{2}
}
func (m *ClientTransactionGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientTransactionGetRequest.Unmarshal(m, b)
}
func (m *ClientTransactionGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientTransactionGetRequest.Marshal(b, m, deterministic)
}
func (dst *ClientTransactionGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientTransactionGetRequest.Merge(dst, src)
}
func (m *ClientTransactionGetRequest) XXX_Size() int {
	return xxx_messageInfo_ClientTransactionGetRequest.Size(m)
}
func (m *ClientTransactionGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientTransactionGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClientTransactionGetRequest proto.InternalMessageInfo

func (m *ClientTransactionGetRequest) GetTransactionId() string {
	if m != nil {
		return m.TransactionId
	}
	return ""
}

// A response that returns the txn specified by a ClientTransactionGetRequest.
//
// Statuses:
//   * OK - everything worked as expected, txn has been fetched
//   * INTERNAL_ERROR - general error, such as protobuf failing to deserialize
//   * NO_RESOURCE - no txn with the specified id exists
type ClientTransactionGetResponse struct {
	Status               ClientTransactionGetResponse_Status `protobuf:"varint,1,opt,name=status,enum=ClientTransactionGetResponse_Status" json:"status,omitempty"`
	Transaction          *transaction_pb2.Transaction        `protobuf:"bytes,2,opt,name=transaction" json:"transaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *ClientTransactionGetResponse) Reset()         { *m = ClientTransactionGetResponse{} }
func (m *ClientTransactionGetResponse) String() string { return proto.CompactTextString(m) }
func (*ClientTransactionGetResponse) ProtoMessage()    {}
func (*ClientTransactionGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_client_transaction_754fcaed5986d902, []int{3}
}
func (m *ClientTransactionGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientTransactionGetResponse.Unmarshal(m, b)
}
func (m *ClientTransactionGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientTransactionGetResponse.Marshal(b, m, deterministic)
}
func (dst *ClientTransactionGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientTransactionGetResponse.Merge(dst, src)
}
func (m *ClientTransactionGetResponse) XXX_Size() int {
	return xxx_messageInfo_ClientTransactionGetResponse.Size(m)
}
func (m *ClientTransactionGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientTransactionGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClientTransactionGetResponse proto.InternalMessageInfo

func (m *ClientTransactionGetResponse) GetStatus() ClientTransactionGetResponse_Status {
	if m != nil {
		return m.Status
	}
	return ClientTransactionGetResponse_STATUS_UNSET
}

func (m *ClientTransactionGetResponse) GetTransaction() *transaction_pb2.Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

func init() {
	proto.RegisterType((*ClientTransactionListRequest)(nil), "ClientTransactionListRequest")
	proto.RegisterType((*ClientTransactionListResponse)(nil), "ClientTransactionListResponse")
	proto.RegisterType((*ClientTransactionGetRequest)(nil), "ClientTransactionGetRequest")
	proto.RegisterType((*ClientTransactionGetResponse)(nil), "ClientTransactionGetResponse")
	proto.RegisterEnum("ClientTransactionListResponse_Status", ClientTransactionListResponse_Status_name, ClientTransactionListResponse_Status_value)
	proto.RegisterEnum("ClientTransactionGetResponse_Status", ClientTransactionGetResponse_Status_name, ClientTransactionGetResponse_Status_value)
}

func init() {
	proto.RegisterFile("github.com/daludaluking/sawtooth_sdk/protobuf/client_transaction_pb2/client_transaction.proto", fileDescriptor_client_transaction_754fcaed5986d902)
}

var fileDescriptor_client_transaction_754fcaed5986d902 = []byte{
	// 503 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xdd, 0x8e, 0xd2, 0x40,
	0x14, 0xc7, 0x2d, 0x60, 0x91, 0x53, 0xb6, 0x3b, 0x19, 0xb3, 0x4a, 0xfc, 0x48, 0x48, 0xe3, 0x46,
	0x6e, 0xb6, 0xab, 0xf5, 0xc2, 0x1b, 0xbd, 0xa8, 0xd0, 0x90, 0x46, 0xd2, 0x92, 0x69, 0xd1, 0xe8,
	0xcd, 0xa4, 0xd0, 0xba, 0xdb, 0x2c, 0xe9, 0x60, 0x67, 0x88, 0xcf, 0xe2, 0xcb, 0xf8, 0x36, 0xbe,
	0x81, 0x0f, 0x60, 0xe8, 0xc7, 0x6e, 0x0b, 0x95, 0x0b, 0x2f, 0xfb, 0xe7, 0x77, 0xbe, 0xfe, 0xe7,
	0x0c, 0x60, 0xf1, 0xe0, 0x87, 0x60, 0x4c, 0x5c, 0x53, 0x1e, 0xde, 0x5c, 0x6e, 0x52, 0x26, 0xd8,
	0x72, 0xfb, 0xed, 0x72, 0xb5, 0x8e, 0xa3, 0x44, 0x50, 0x91, 0x06, 0x09, 0x0f, 0x56, 0x22, 0x66,
	0x09, 0xdd, 0x2c, 0x8d, 0x06, 0x59, 0xcf, 0x42, 0x9e, 0xbc, 0x6d, 0x4e, 0xb3, 0x1f, 0x7f, 0x18,
	0x38, 0x3d, 0x5a, 0x7f, 0x1d, 0x73, 0x41, 0x57, 0x2c, 0x11, 0x29, 0x5b, 0x57, 0x1b, 0xa8, 0xea,
	0x79, 0x22, 0xed, 0x97, 0x04, 0xcf, 0xc6, 0xd9, 0xaf, 0xfe, 0x5d, 0x91, 0x59, 0xcc, 0x05, 0x89,
	0xbe, 0x6f, 0x23, 0x2e, 0xf0, 0x63, 0xe8, 0x5e, 0x47, 0x41, 0x48, 0xe3, 0x70, 0x20, 0x0d, 0xa5,
	0x51, 0x8f, 0xc8, 0xbb, 0x4f, 0x3b, 0xc4, 0x2f, 0xe1, 0xb4, 0xda, 0x67, 0x1c, 0xf2, 0x41, 0x6b,
	0xd8, 0x1e, 0xf5, 0x88, 0x5a, 0x91, 0xed, 0x90, 0xe3, 0x0b, 0x90, 0x37, 0xc1, 0x55, 0x9c, 0x5c,
	0x0d, 0xda, 0x43, 0x69, 0xa4, 0x18, 0x67, 0x7a, 0x5e, 0x70, 0x9e, 0x89, 0xe3, 0xbc, 0x1d, 0x4e,
	0x0a, 0x08, 0x5f, 0x40, 0x97, 0xb3, 0x54, 0xec, 0xf8, 0xce, 0xb0, 0x3d, 0x52, 0x8c, 0x87, 0x05,
	0xef, 0xb1, 0x54, 0xdc, 0xd2, 0x25, 0xa3, 0xfd, 0x69, 0xc1, 0xf3, 0x7f, 0x0c, 0xc0, 0x37, 0x2c,
	0xe1, 0x11, 0x7e, 0x0f, 0x32, 0x17, 0x81, 0xd8, 0xf2, 0x6c, 0x00, 0xd5, 0x38, 0xd7, 0x8f, 0xf2,
	0xba, 0x97, 0xc1, 0xa4, 0x08, 0xc2, 0xaf, 0xa0, 0x5f, 0x19, 0x28, 0x1f, 0x52, 0x31, 0xfa, 0x7a,
	0x25, 0x9c, 0xd4, 0x88, 0xaa, 0x65, 0xed, 0x9a, 0x65, 0x77, 0x4e, 0x74, 0x1a, 0x9c, 0x28, 0x1b,
	0x28, 0x9d, 0xd0, 0x7e, 0x4a, 0x20, 0xe7, 0xcd, 0x60, 0x04, 0x7d, 0xcf, 0x37, 0xfd, 0x85, 0x47,
	0x17, 0x8e, 0x67, 0xf9, 0xe8, 0x1e, 0x96, 0xa1, 0xe5, 0x7e, 0x44, 0x12, 0xc6, 0xa0, 0xda, 0x8e,
	0x6f, 0x11, 0xc7, 0x9c, 0x51, 0x8b, 0x10, 0x97, 0xa0, 0x16, 0x3e, 0x81, 0x9e, 0xe3, 0xfa, 0x94,
	0x58, 0xe6, 0xe4, 0x0b, 0x6a, 0x63, 0x05, 0xba, 0x8e, 0x4b, 0x89, 0xeb, 0xfa, 0xa8, 0x83, 0x4f,
	0x41, 0xd9, 0x7d, 0x58, 0x9e, 0xbb, 0x20, 0x63, 0x0b, 0xdd, 0xcf, 0x13, 0x7c, 0x32, 0x67, 0xf6,
	0x84, 0xce, 0xcd, 0xa9, 0xed, 0x4c, 0x91, 0xbc, 0x2b, 0x57, 0x6a, 0x9e, 0x4b, 0x7c, 0xd4, 0xc5,
	0x2a, 0x40, 0xa9, 0xd8, 0x13, 0xf4, 0x40, 0x9b, 0xc0, 0xd3, 0x03, 0x17, 0xa7, 0xd1, 0xed, 0xd5,
	0x9c, 0x83, 0x5a, 0x3f, 0x8e, 0xe2, 0x78, 0x4e, 0x6a, 0xb7, 0xa1, 0xfd, 0x6e, 0xba, 0xbe, 0x2c,
	0x4d, 0xb1, 0xbb, 0x77, 0x7b, 0xbb, 0x7b, 0xa1, 0x1f, 0xc3, 0xf7, 0x57, 0xa7, 0x83, 0x52, 0xa9,
	0x37, 0x68, 0x65, 0xa6, 0xd7, 0x37, 0x57, 0x05, 0xb4, 0xcf, 0xff, 0xe9, 0xf7, 0x81, 0xa7, 0x7b,
	0x6e, 0x7d, 0x78, 0x0d, 0x67, 0xe5, 0x83, 0xd5, 0x79, 0x78, 0xa3, 0x97, 0x0f, 0x76, 0x2e, 0x7d,
	0x7d, 0xd4, 0xfc, 0x9f, 0xb1, 0x94, 0x33, 0xe6, 0xcd, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x54,
	0x1b, 0xaa, 0x41, 0x6a, 0x04, 0x00, 0x00,
}
