// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/daludaluking/sawtooth_sdk/protobuf/authorization_pb2/authorization.proto

package authorization_pb2

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RoleType int32

const (
	RoleType_ROLE_TYPE_UNSET RoleType = 0
	// A shorthand request for asking for all allowed roles.
	RoleType_ALL RoleType = 1
	// Role defining validator to validator communication
	RoleType_NETWORK RoleType = 2
)

var RoleType_name = map[int32]string{
	0: "ROLE_TYPE_UNSET",
	1: "ALL",
	2: "NETWORK",
}
var RoleType_value = map[string]int32{
	"ROLE_TYPE_UNSET": 0,
	"ALL":             1,
	"NETWORK":         2,
}

func (x RoleType) String() string {
	return proto.EnumName(RoleType_name, int32(x))
}
func (RoleType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_authorization_e576a43fe1d5b0d5, []int{0}
}

// Whether the connection can participate in authorization
type ConnectionResponse_Status int32

const (
	ConnectionResponse_STATUS_UNSET ConnectionResponse_Status = 0
	ConnectionResponse_OK           ConnectionResponse_Status = 1
	ConnectionResponse_ERROR        ConnectionResponse_Status = 2
)

var ConnectionResponse_Status_name = map[int32]string{
	0: "STATUS_UNSET",
	1: "OK",
	2: "ERROR",
}
var ConnectionResponse_Status_value = map[string]int32{
	"STATUS_UNSET": 0,
	"OK":           1,
	"ERROR":        2,
}

func (x ConnectionResponse_Status) String() string {
	return proto.EnumName(ConnectionResponse_Status_name, int32(x))
}
func (ConnectionResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_authorization_e576a43fe1d5b0d5, []int{1, 0}
}

// Authorization Type required for the authorization procedure
type ConnectionResponse_AuthorizationType int32

const (
	ConnectionResponse_AUTHORIZATION_TYPE_UNSET ConnectionResponse_AuthorizationType = 0
	ConnectionResponse_TRUST                    ConnectionResponse_AuthorizationType = 1
	ConnectionResponse_CHALLENGE                ConnectionResponse_AuthorizationType = 2
)

var ConnectionResponse_AuthorizationType_name = map[int32]string{
	0: "AUTHORIZATION_TYPE_UNSET",
	1: "TRUST",
	2: "CHALLENGE",
}
var ConnectionResponse_AuthorizationType_value = map[string]int32{
	"AUTHORIZATION_TYPE_UNSET": 0,
	"TRUST":                    1,
	"CHALLENGE":                2,
}

func (x ConnectionResponse_AuthorizationType) String() string {
	return proto.EnumName(ConnectionResponse_AuthorizationType_name, int32(x))
}
func (ConnectionResponse_AuthorizationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_authorization_e576a43fe1d5b0d5, []int{1, 1}
}

type ConnectionRequest struct {
	// This is the first message that must be sent to start off authorization.
	// The endpoint of the connection.
	Endpoint             string   `protobuf:"bytes,1,opt,name=endpoint" json:"endpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectionRequest) Reset()         { *m = ConnectionRequest{} }
func (m *ConnectionRequest) String() string { return proto.CompactTextString(m) }
func (*ConnectionRequest) ProtoMessage()    {}
func (*ConnectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_authorization_e576a43fe1d5b0d5, []int{0}
}
func (m *ConnectionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionRequest.Unmarshal(m, b)
}
func (m *ConnectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionRequest.Marshal(b, m, deterministic)
}
func (dst *ConnectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionRequest.Merge(dst, src)
}
func (m *ConnectionRequest) XXX_Size() int {
	return xxx_messageInfo_ConnectionRequest.Size(m)
}
func (m *ConnectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionRequest proto.InternalMessageInfo

func (m *ConnectionRequest) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

type ConnectionResponse struct {
	Roles                []*ConnectionResponse_RoleEntry `protobuf:"bytes,1,rep,name=roles" json:"roles,omitempty"`
	Status               ConnectionResponse_Status       `protobuf:"varint,2,opt,name=status,enum=ConnectionResponse_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *ConnectionResponse) Reset()         { *m = ConnectionResponse{} }
func (m *ConnectionResponse) String() string { return proto.CompactTextString(m) }
func (*ConnectionResponse) ProtoMessage()    {}
func (*ConnectionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_authorization_e576a43fe1d5b0d5, []int{1}
}
func (m *ConnectionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionResponse.Unmarshal(m, b)
}
func (m *ConnectionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionResponse.Marshal(b, m, deterministic)
}
func (dst *ConnectionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionResponse.Merge(dst, src)
}
func (m *ConnectionResponse) XXX_Size() int {
	return xxx_messageInfo_ConnectionResponse.Size(m)
}
func (m *ConnectionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionResponse proto.InternalMessageInfo

func (m *ConnectionResponse) GetRoles() []*ConnectionResponse_RoleEntry {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *ConnectionResponse) GetStatus() ConnectionResponse_Status {
	if m != nil {
		return m.Status
	}
	return ConnectionResponse_STATUS_UNSET
}

type ConnectionResponse_RoleEntry struct {
	// The role type for this role entry
	Role RoleType `protobuf:"varint,1,opt,name=role,enum=RoleType" json:"role,omitempty"`
	// The Authorization Type required for the above role
	AuthType             ConnectionResponse_AuthorizationType `protobuf:"varint,2,opt,name=auth_type,json=authType,enum=ConnectionResponse_AuthorizationType" json:"auth_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *ConnectionResponse_RoleEntry) Reset()         { *m = ConnectionResponse_RoleEntry{} }
func (m *ConnectionResponse_RoleEntry) String() string { return proto.CompactTextString(m) }
func (*ConnectionResponse_RoleEntry) ProtoMessage()    {}
func (*ConnectionResponse_RoleEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_authorization_e576a43fe1d5b0d5, []int{1, 0}
}
func (m *ConnectionResponse_RoleEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionResponse_RoleEntry.Unmarshal(m, b)
}
func (m *ConnectionResponse_RoleEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionResponse_RoleEntry.Marshal(b, m, deterministic)
}
func (dst *ConnectionResponse_RoleEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionResponse_RoleEntry.Merge(dst, src)
}
func (m *ConnectionResponse_RoleEntry) XXX_Size() int {
	return xxx_messageInfo_ConnectionResponse_RoleEntry.Size(m)
}
func (m *ConnectionResponse_RoleEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionResponse_RoleEntry.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionResponse_RoleEntry proto.InternalMessageInfo

func (m *ConnectionResponse_RoleEntry) GetRole() RoleType {
	if m != nil {
		return m.Role
	}
	return RoleType_ROLE_TYPE_UNSET
}

func (m *ConnectionResponse_RoleEntry) GetAuthType() ConnectionResponse_AuthorizationType {
	if m != nil {
		return m.AuthType
	}
	return ConnectionResponse_AUTHORIZATION_TYPE_UNSET
}

type AuthorizationTrustRequest struct {
	// A set of requested RoleTypes
	Roles                []RoleType `protobuf:"varint,1,rep,packed,name=roles,enum=RoleType" json:"roles,omitempty"`
	PublicKey            string     `protobuf:"bytes,2,opt,name=public_key,json=publicKey" json:"public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AuthorizationTrustRequest) Reset()         { *m = AuthorizationTrustRequest{} }
func (m *AuthorizationTrustRequest) String() string { return proto.CompactTextString(m) }
func (*AuthorizationTrustRequest) ProtoMessage()    {}
func (*AuthorizationTrustRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_authorization_e576a43fe1d5b0d5, []int{2}
}
func (m *AuthorizationTrustRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthorizationTrustRequest.Unmarshal(m, b)
}
func (m *AuthorizationTrustRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthorizationTrustRequest.Marshal(b, m, deterministic)
}
func (dst *AuthorizationTrustRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorizationTrustRequest.Merge(dst, src)
}
func (m *AuthorizationTrustRequest) XXX_Size() int {
	return xxx_messageInfo_AuthorizationTrustRequest.Size(m)
}
func (m *AuthorizationTrustRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorizationTrustRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorizationTrustRequest proto.InternalMessageInfo

func (m *AuthorizationTrustRequest) GetRoles() []RoleType {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *AuthorizationTrustRequest) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

type AuthorizationTrustResponse struct {
	// The actual set the requester has access to
	Roles                []RoleType `protobuf:"varint,1,rep,packed,name=roles,enum=RoleType" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AuthorizationTrustResponse) Reset()         { *m = AuthorizationTrustResponse{} }
func (m *AuthorizationTrustResponse) String() string { return proto.CompactTextString(m) }
func (*AuthorizationTrustResponse) ProtoMessage()    {}
func (*AuthorizationTrustResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_authorization_e576a43fe1d5b0d5, []int{3}
}
func (m *AuthorizationTrustResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthorizationTrustResponse.Unmarshal(m, b)
}
func (m *AuthorizationTrustResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthorizationTrustResponse.Marshal(b, m, deterministic)
}
func (dst *AuthorizationTrustResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorizationTrustResponse.Merge(dst, src)
}
func (m *AuthorizationTrustResponse) XXX_Size() int {
	return xxx_messageInfo_AuthorizationTrustResponse.Size(m)
}
func (m *AuthorizationTrustResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorizationTrustResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorizationTrustResponse proto.InternalMessageInfo

func (m *AuthorizationTrustResponse) GetRoles() []RoleType {
	if m != nil {
		return m.Roles
	}
	return nil
}

type AuthorizationViolation struct {
	// The Role the requester did not have access to
	Violation            RoleType `protobuf:"varint,1,opt,name=violation,enum=RoleType" json:"violation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthorizationViolation) Reset()         { *m = AuthorizationViolation{} }
func (m *AuthorizationViolation) String() string { return proto.CompactTextString(m) }
func (*AuthorizationViolation) ProtoMessage()    {}
func (*AuthorizationViolation) Descriptor() ([]byte, []int) {
	return fileDescriptor_authorization_e576a43fe1d5b0d5, []int{4}
}
func (m *AuthorizationViolation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthorizationViolation.Unmarshal(m, b)
}
func (m *AuthorizationViolation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthorizationViolation.Marshal(b, m, deterministic)
}
func (dst *AuthorizationViolation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorizationViolation.Merge(dst, src)
}
func (m *AuthorizationViolation) XXX_Size() int {
	return xxx_messageInfo_AuthorizationViolation.Size(m)
}
func (m *AuthorizationViolation) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorizationViolation.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorizationViolation proto.InternalMessageInfo

func (m *AuthorizationViolation) GetViolation() RoleType {
	if m != nil {
		return m.Violation
	}
	return RoleType_ROLE_TYPE_UNSET
}

type AuthorizationChallengeRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthorizationChallengeRequest) Reset()         { *m = AuthorizationChallengeRequest{} }
func (m *AuthorizationChallengeRequest) String() string { return proto.CompactTextString(m) }
func (*AuthorizationChallengeRequest) ProtoMessage()    {}
func (*AuthorizationChallengeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_authorization_e576a43fe1d5b0d5, []int{5}
}
func (m *AuthorizationChallengeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthorizationChallengeRequest.Unmarshal(m, b)
}
func (m *AuthorizationChallengeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthorizationChallengeRequest.Marshal(b, m, deterministic)
}
func (dst *AuthorizationChallengeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorizationChallengeRequest.Merge(dst, src)
}
func (m *AuthorizationChallengeRequest) XXX_Size() int {
	return xxx_messageInfo_AuthorizationChallengeRequest.Size(m)
}
func (m *AuthorizationChallengeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorizationChallengeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorizationChallengeRequest proto.InternalMessageInfo

type AuthorizationChallengeResponse struct {
	// Random payload that the connecting node must sign
	Payload              []byte   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthorizationChallengeResponse) Reset()         { *m = AuthorizationChallengeResponse{} }
func (m *AuthorizationChallengeResponse) String() string { return proto.CompactTextString(m) }
func (*AuthorizationChallengeResponse) ProtoMessage()    {}
func (*AuthorizationChallengeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_authorization_e576a43fe1d5b0d5, []int{6}
}
func (m *AuthorizationChallengeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthorizationChallengeResponse.Unmarshal(m, b)
}
func (m *AuthorizationChallengeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthorizationChallengeResponse.Marshal(b, m, deterministic)
}
func (dst *AuthorizationChallengeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorizationChallengeResponse.Merge(dst, src)
}
func (m *AuthorizationChallengeResponse) XXX_Size() int {
	return xxx_messageInfo_AuthorizationChallengeResponse.Size(m)
}
func (m *AuthorizationChallengeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorizationChallengeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorizationChallengeResponse proto.InternalMessageInfo

func (m *AuthorizationChallengeResponse) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type AuthorizationChallengeSubmit struct {
	// public key of node
	PublicKey string `protobuf:"bytes,1,opt,name=public_key,json=publicKey" json:"public_key,omitempty"`
	// signature derived from signing the challenge payload
	Signature string `protobuf:"bytes,3,opt,name=signature" json:"signature,omitempty"`
	// A set of requested Roles
	Roles                []RoleType `protobuf:"varint,4,rep,packed,name=roles,enum=RoleType" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AuthorizationChallengeSubmit) Reset()         { *m = AuthorizationChallengeSubmit{} }
func (m *AuthorizationChallengeSubmit) String() string { return proto.CompactTextString(m) }
func (*AuthorizationChallengeSubmit) ProtoMessage()    {}
func (*AuthorizationChallengeSubmit) Descriptor() ([]byte, []int) {
	return fileDescriptor_authorization_e576a43fe1d5b0d5, []int{7}
}
func (m *AuthorizationChallengeSubmit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthorizationChallengeSubmit.Unmarshal(m, b)
}
func (m *AuthorizationChallengeSubmit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthorizationChallengeSubmit.Marshal(b, m, deterministic)
}
func (dst *AuthorizationChallengeSubmit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorizationChallengeSubmit.Merge(dst, src)
}
func (m *AuthorizationChallengeSubmit) XXX_Size() int {
	return xxx_messageInfo_AuthorizationChallengeSubmit.Size(m)
}
func (m *AuthorizationChallengeSubmit) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorizationChallengeSubmit.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorizationChallengeSubmit proto.InternalMessageInfo

func (m *AuthorizationChallengeSubmit) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *AuthorizationChallengeSubmit) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *AuthorizationChallengeSubmit) GetRoles() []RoleType {
	if m != nil {
		return m.Roles
	}
	return nil
}

type AuthorizationChallengeResult struct {
	// The approved roles for that connection
	Roles                []RoleType `protobuf:"varint,1,rep,packed,name=roles,enum=RoleType" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AuthorizationChallengeResult) Reset()         { *m = AuthorizationChallengeResult{} }
func (m *AuthorizationChallengeResult) String() string { return proto.CompactTextString(m) }
func (*AuthorizationChallengeResult) ProtoMessage()    {}
func (*AuthorizationChallengeResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_authorization_e576a43fe1d5b0d5, []int{8}
}
func (m *AuthorizationChallengeResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthorizationChallengeResult.Unmarshal(m, b)
}
func (m *AuthorizationChallengeResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthorizationChallengeResult.Marshal(b, m, deterministic)
}
func (dst *AuthorizationChallengeResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorizationChallengeResult.Merge(dst, src)
}
func (m *AuthorizationChallengeResult) XXX_Size() int {
	return xxx_messageInfo_AuthorizationChallengeResult.Size(m)
}
func (m *AuthorizationChallengeResult) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorizationChallengeResult.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorizationChallengeResult proto.InternalMessageInfo

func (m *AuthorizationChallengeResult) GetRoles() []RoleType {
	if m != nil {
		return m.Roles
	}
	return nil
}

func init() {
	proto.RegisterType((*ConnectionRequest)(nil), "ConnectionRequest")
	proto.RegisterType((*ConnectionResponse)(nil), "ConnectionResponse")
	proto.RegisterType((*ConnectionResponse_RoleEntry)(nil), "ConnectionResponse.RoleEntry")
	proto.RegisterType((*AuthorizationTrustRequest)(nil), "AuthorizationTrustRequest")
	proto.RegisterType((*AuthorizationTrustResponse)(nil), "AuthorizationTrustResponse")
	proto.RegisterType((*AuthorizationViolation)(nil), "AuthorizationViolation")
	proto.RegisterType((*AuthorizationChallengeRequest)(nil), "AuthorizationChallengeRequest")
	proto.RegisterType((*AuthorizationChallengeResponse)(nil), "AuthorizationChallengeResponse")
	proto.RegisterType((*AuthorizationChallengeSubmit)(nil), "AuthorizationChallengeSubmit")
	proto.RegisterType((*AuthorizationChallengeResult)(nil), "AuthorizationChallengeResult")
	proto.RegisterEnum("RoleType", RoleType_name, RoleType_value)
	proto.RegisterEnum("ConnectionResponse_Status", ConnectionResponse_Status_name, ConnectionResponse_Status_value)
	proto.RegisterEnum("ConnectionResponse_AuthorizationType", ConnectionResponse_AuthorizationType_name, ConnectionResponse_AuthorizationType_value)
}

func init() {
	proto.RegisterFile("github.com/daludaluking/sawtooth_sdk/protobuf/authorization_pb2/authorization.proto", fileDescriptor_authorization_e576a43fe1d5b0d5)
}

var fileDescriptor_authorization_e576a43fe1d5b0d5 = []byte{
	// 532 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0xef, 0x6b, 0xd3, 0x40,
	0x18, 0x36, 0xe9, 0xfa, 0xe3, 0xde, 0xcd, 0x99, 0x9e, 0x28, 0xb1, 0xb4, 0xae, 0x04, 0xc4, 0x22,
	0xda, 0x42, 0x87, 0x5f, 0x14, 0x91, 0xac, 0x04, 0x37, 0x5a, 0x9a, 0x71, 0x49, 0x15, 0xe7, 0x87,
	0x90, 0xae, 0xe7, 0x1a, 0x1a, 0x73, 0x31, 0x77, 0x51, 0x22, 0xfe, 0xc3, 0xfe, 0x17, 0xd2, 0x34,
	0xe9, 0x9a, 0xb5, 0x65, 0xdf, 0x72, 0xcf, 0x3d, 0xcf, 0xf3, 0xde, 0xfb, 0xbc, 0xe1, 0x85, 0xf7,
	0xdc, 0xfd, 0x2d, 0x18, 0x13, 0x73, 0x87, 0xcf, 0x16, 0xbd, 0x30, 0x62, 0x82, 0x4d, 0xe3, 0xef,
	0x3d, 0x37, 0x16, 0x73, 0x16, 0x79, 0x7f, 0x5c, 0xe1, 0xb1, 0xc0, 0x09, 0xa7, 0xfd, 0x22, 0xd2,
	0x4d, 0x89, 0x5a, 0x0f, 0xea, 0x03, 0x16, 0x04, 0xf4, 0x7a, 0x89, 0x11, 0xfa, 0x33, 0xa6, 0x5c,
	0xe0, 0x06, 0xd4, 0x68, 0x30, 0x0b, 0x99, 0x17, 0x08, 0x55, 0x6a, 0x4b, 0x1d, 0x44, 0xd6, 0x67,
	0xed, 0x9f, 0x0c, 0x78, 0x53, 0xc1, 0x43, 0x16, 0x70, 0x8a, 0x4f, 0xa1, 0x1c, 0x31, 0x9f, 0x72,
	0x55, 0x6a, 0x97, 0x3a, 0x87, 0xfd, 0x56, 0x77, 0x9b, 0xd3, 0x25, 0xcc, 0xa7, 0x46, 0x20, 0xa2,
	0x84, 0xac, 0xb8, 0xb8, 0x0f, 0x15, 0x2e, 0x5c, 0x11, 0x73, 0x55, 0x6e, 0x4b, 0x9d, 0xe3, 0x7e,
	0x63, 0x97, 0xca, 0x4a, 0x19, 0x24, 0x63, 0x36, 0x02, 0x40, 0x6b, 0x1f, 0xdc, 0x82, 0x83, 0xa5,
	0x53, 0xfa, 0xc8, 0xe3, 0x3e, 0x4a, 0x2b, 0xd8, 0x49, 0x48, 0x49, 0x0a, 0xe3, 0x33, 0x40, 0xcb,
	0x9e, 0x1d, 0x91, 0x84, 0x34, 0x2b, 0xf1, 0x62, 0x57, 0x09, 0x7d, 0x33, 0x98, 0x54, 0x5f, 0x5b,
	0xea, 0x96, 0x5f, 0xda, 0x1b, 0xa8, 0xac, 0x5e, 0x80, 0x15, 0x38, 0xb2, 0x6c, 0xdd, 0x9e, 0x58,
	0xce, 0x64, 0x6c, 0x19, 0xb6, 0xf2, 0x00, 0x57, 0x40, 0x36, 0x87, 0x8a, 0x84, 0x11, 0x94, 0x0d,
	0x42, 0x4c, 0xa2, 0xc8, 0xda, 0x10, 0xea, 0x5b, 0x6e, 0xb8, 0x09, 0xaa, 0x3e, 0xb1, 0xcf, 0x4d,
	0x72, 0x71, 0xa5, 0xdb, 0x17, 0xe6, 0xd8, 0xb1, 0xbf, 0x5e, 0x1a, 0x6b, 0x17, 0x04, 0x65, 0x9b,
	0x4c, 0x2c, 0x5b, 0x91, 0xf0, 0x43, 0x40, 0x83, 0x73, 0x7d, 0x34, 0x32, 0xc6, 0x9f, 0x0c, 0x45,
	0xd6, 0xbe, 0xc1, 0xb3, 0xa2, 0x59, 0x14, 0x73, 0x91, 0x0f, 0xe9, 0x64, 0x33, 0xf1, 0x42, 0xf3,
	0x59, 0xba, 0x2d, 0x80, 0x30, 0x9e, 0xfa, 0xde, 0xb5, 0xb3, 0xa0, 0x49, 0xda, 0x3e, 0x22, 0x68,
	0x85, 0x0c, 0x69, 0xa2, 0x7d, 0x80, 0xc6, 0x2e, 0xf3, 0x6c, 0x9e, 0xf7, 0xb9, 0x6b, 0x3a, 0x3c,
	0x2d, 0xc8, 0x3f, 0x7b, 0xcc, 0x4f, 0x3f, 0xf0, 0x4b, 0x40, 0xbf, 0xf2, 0xc3, 0xf6, 0x64, 0x6e,
	0xef, 0xb4, 0x13, 0x68, 0x15, 0x2c, 0x06, 0x73, 0xd7, 0xf7, 0x69, 0x70, 0x43, 0xb3, 0x16, 0xb5,
	0x77, 0xf0, 0x7c, 0x1f, 0x21, 0x7b, 0xa6, 0x0a, 0xd5, 0xd0, 0x4d, 0x7c, 0xe6, 0xce, 0xd2, 0x4a,
	0x47, 0x24, 0x3f, 0x6a, 0x7f, 0xa1, 0xb9, 0x5b, 0x6b, 0xc5, 0xd3, 0x1f, 0x9e, 0xb8, 0x93, 0x8e,
	0x74, 0x27, 0x1d, 0xdc, 0x04, 0xc4, 0xbd, 0x9b, 0xc0, 0x15, 0x71, 0x44, 0xd5, 0xd2, 0xea, 0x76,
	0x0d, 0xdc, 0xa6, 0x73, 0xb0, 0x27, 0x9d, 0x8f, 0xfb, 0xaa, 0x13, 0xca, 0x63, 0xff, 0xfe, 0xe1,
	0xbd, 0x7a, 0x0b, 0xb5, 0x1c, 0xc2, 0x8f, 0xe1, 0x11, 0x31, 0x47, 0x46, 0xf1, 0xaf, 0xa9, 0x42,
	0x49, 0x1f, 0x8d, 0x14, 0x09, 0x1f, 0x42, 0x75, 0x6c, 0xd8, 0x5f, 0x4c, 0x32, 0x54, 0xe4, 0xb3,
	0xd7, 0xf0, 0x24, 0xdf, 0x06, 0x5d, 0x3e, 0x5b, 0x74, 0xf3, 0x6d, 0x70, 0x29, 0x5d, 0xd5, 0xb7,
	0x16, 0xc2, 0xb4, 0x92, 0x5e, 0x9f, 0xfe, 0x0f, 0x00, 0x00, 0xff, 0xff, 0x72, 0xeb, 0x6d, 0xac,
	0x42, 0x04, 0x00, 0x00,
}
